name: Download dataset files
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download playlist-sample-ds1.csv
        run: |
          curl -o -k playlist-sample-ds1.csv http://homepages.dcc.ufmg.br/~cunha/hosted/compsci401-s3-23-datasets/playlist-sample-ds1.csv
      - name: Download playlist-sample-ds2.csv
        run: |
          curl -o -k playlist-sample-ds2.csv http://homepages.dcc.ufmg.br/~cunha/hosted/compsci401-s3-23-datasets/playlist-sample-ds2.csv
      - name: Download songs.csv
        run: |
          curl -o -k songs.csv http://homepages.dcc.ufmg.br/~cunha/hosted/compsci401-s3-23-datasets/songs.csv
